### ISSUE TITLE
Feature Backlog for BC Government Directory

### ISSUE THREAD

**Issue by bradhead** [Quartech/QSLContacts#55]
This is the feature backlog we had in mind after delivering the MVP. 
1.	Enhance VCard support to work better with popular browsers. It has some issues with Chrome
2.	Add hyperlinked organization structure to easily navigate through the organizational reporting structure (i.e. which director reports to which exec director. The orgunit hints at this, but when more than one ED in an org-unit can't resolve. 
3.	Feature to bookmark either contact or organization, or org unit. 
4.	Ability to ‘save search’, similar to ‘favourites, but a search with a customized label.
5.	Filter by organization
6.	Enhance search to support excluding words when zero matches found to find ‘possible matches’
7.	Enhance search to support phrases as, such as “Ministry of Finance” to avoid finding Finance departments in other ministries. 
8.	Improve client-side content management to support functionality when disconnected from the Internet.   - using HTML 5 local storage of the JSON.

Necessary tweaks to the XML Schema to support some of these features:

a.	Of these, (2) would require a more information be supplied by the content sources. 
b.	Additionally, having the IDIR-like organization abbreviation “CITZ” for example.
c.	Also codified roles would be useful, “ADM” for Assistant DM, “ED” for Exec. Director, and so on, as well as the human-readable job/role title.
d.	Codifying the phone so we know if it’s a mobile or land line and if it can receive texts would allow us to add the ability to text the contact, as you suggested using the sms URI schme:
a.	E.g. sms:+18005551212

**Comment by devinleighsmith** [comment]
Note, I've itemized the above to make it easier to track progress on each issue. Leaving this issue here for historical purposes.

**Comment by bradhead** [comment]
let's close this now with the issues/features broken out
